name: dartastic_opentelemetry
description: Dartastic.io's OpenTelemetry SDK for Dart
version: 1.0.1
repository: https://github.com/MindfulSoftwareLLC/dartastic_opentelemetry.git
homepage: https://dartastic.io

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.16.0
  grpc: ^3.2.4
  opentelemetry_api:
    hosted:
      name: opentelemetry_api
      url: https://dartastic-dart-services-6djqlrsgkq-uc.a.run.app
    version:
      1.0.1
  protobuf: ^3.1.0
  fixnum: ^1.1.1
  synchronized: ^3.3.1

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.1.1
  test: ^1.25.14
  coverage: ^1.11.1
  protoc_plugin: ^21.1.2  # For generating Dart proto files
